# Generated by deskosctl from plan.json. Do not edit.
#
# Workstation: deskos-core-centos10
# Platform:    centos-stream-10 (CentOS Stream 10)

FROM quay.io/centos-bootc/centos-bootc:stream10@sha256:39ee41e7f87c09484603bc7f37550f0a45ccd01c30b1adf1d2cd0666f9c0ca98

# RPM groups
RUN --mount=type=tmpfs,target=/var/lib/rhsm \
    --mount=type=tmpfs,target=/var/log/rhsm \
    if [ -e /etc/yum.repos.d/redhat.repo ]; then echo 'refusing to run dnf: /etc/yum.repos.d/redhat.repo already exists' >&2; exit 1; fi \
    && dnf -y group install \
        'workstation-product-environment' \
    && dnf clean all \
    && rm -f /etc/yum.repos.d/redhat.repo

# RPM packages
RUN --mount=type=tmpfs,target=/var/lib/rhsm \
    --mount=type=tmpfs,target=/var/log/rhsm \
    if [ -e /etc/yum.repos.d/redhat.repo ]; then echo 'refusing to run dnf: /etc/yum.repos.d/redhat.repo already exists' >&2; exit 1; fi \
    && dnf -y install \
        'NetworkManager' \
        'bootc' \
        'firefox' \
        'firewalld' \
        'flatpak' \
        'gnome-shell-extension-dash-to-dock' \
        'plymouth' \
        'plymouth-scripts' \
        'plymouth-system-theme' \
        'plymouth-theme-spinner' \
    && dnf clean all \
    && rm -f /etc/yum.repos.d/redhat.repo

# Image files
COPY rootfs/ /

# System configuration
RUN glib-compile-schemas --strict /usr/share/glib-2.0/schemas \
    && dconf update \
    && systemctl enable 'deskos-flatpak-preinstall.service' 'firewalld.service' 'gdm.service' \
    && systemctl set-default 'graphical.target'

# Boot splash theme deskos: package-owned frames from /usr/share/plymouth/themes/spinner, then made the default
RUN set -eu; \
    for f in '/usr/share/plymouth/themes/spinner'/*.png; do \
        [ -f "$f" ] || continue; \
        name="$(basename "$f")"; \
        [ "$name" != 'watermark.png' ] || continue; \
        [ ! -e '/usr/share/plymouth/themes/deskos'/"$name" ] || { echo "$name already exists in /usr/share/plymouth/themes/deskos" >&2; exit 1; }; \
        install -m 0644 "$f" '/usr/share/plymouth/themes/deskos'/"$name"; \
    done; \
    [ -e '/usr/share/plymouth/themes/deskos'/throbber-0001.png ] || { echo 'no two-step throbber frames in /usr/share/plymouth/themes/spinner' >&2; exit 1; }; \
    plymouth-set-default-theme 'deskos'; \
    [ "$(plymouth-set-default-theme)" = 'deskos' ] || { echo 'Plymouth default theme is not deskos' >&2; exit 1; }

# Initramfs: rebuilt for every kernel in the image, with plymouth
RUN set -eu; found=0; \
    for kdir in /usr/lib/modules/*/; do \
        [ -e "${kdir}vmlinuz" ] || continue; \
        kver="$(basename "$kdir")"; \
        env DRACUT_NO_XATTR=1 dracut --force "${kdir}initramfs.img" "$kver"; \
        lsinitrd "${kdir}initramfs.img" | grep -q 'plymouthd' || { echo "plymouth missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd "${kdir}initramfs.img" | grep -qF 'usr/share/plymouth/themes/deskos/deskos.plymouth' || { echo "/usr/share/plymouth/themes/deskos/deskos.plymouth missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd "${kdir}initramfs.img" | grep -qF 'usr/share/plymouth/themes/deskos/watermark.png' || { echo "/usr/share/plymouth/themes/deskos/watermark.png missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd "${kdir}initramfs.img" | grep -qF 'usr/share/plymouth/themes/deskos/throbber-0001.png' || { echo "/usr/share/plymouth/themes/deskos/throbber-0001.png missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd -f etc/plymouth/plymouthd.conf "${kdir}initramfs.img" | grep -qx 'Theme=deskos' || { echo "initramfs of $kver does not select Plymouth theme deskos" >&2; exit 1; }; \
        found=$((found + 1)); \
    done; \
    [ "$found" -gt 0 ] || { echo 'no kernel found under /usr/lib/modules' >&2; exit 1; }

# Cleanup and bootc validation
RUN rm -rf /var/cache/dnf /var/cache/libdnf5 /var/lib/dnf/repos /var/log/dnf* /var/log/hawkey.log /tmp/* /var/tmp/* \
    && bootc container lint

LABEL org.deskos.platform="centos-stream-10" \
      org.deskos.workstation="deskos-core-centos10" \
      org.opencontainers.image.title="DeskOS Core (CentOS Stream 10)"
