# Generated by deskosctl from plan.json. Do not edit.
#
# Workstation: example-devops-rhel10
# Platform:    rhel-10 (Red Hat Enterprise Linux 10)
#
# This artifact must not be publicly redistributed.
# Building requires an entitled build host; credentials are supplied by
# the build environment and are never part of this build context.

FROM registry.redhat.io/rhel10/rhel-bootc:10.2@sha256:d13af792edec939afd7508043b30c3e4e6d3b05570072460baf07f57caf7da90

# RPM groups
RUN --mount=type=tmpfs,target=/var/lib/rhsm \
    --mount=type=tmpfs,target=/var/log/rhsm \
    if [ -e /etc/yum.repos.d/redhat.repo ]; then echo 'refusing to run dnf: /etc/yum.repos.d/redhat.repo already exists' >&2; exit 1; fi \
    && dnf -y group install \
        'workstation-product-environment' \
    && dnf clean all \
    && rm -f /etc/yum.repos.d/redhat.repo

# RPM repositories
COPY repos/ /

# RPM packages
RUN --mount=type=tmpfs,target=/var/lib/rhsm \
    --mount=type=tmpfs,target=/var/log/rhsm \
    if [ -e /etc/yum.repos.d/redhat.repo ]; then echo 'refusing to run dnf: /etc/yum.repos.d/redhat.repo already exists' >&2; exit 1; fi \
    && dnf -y install \
        'NetworkManager' \
        'bootc' \
        'buildah' \
        'cockpit' \
        'cockpit-machines' \
        'code' \
        'firefox' \
        'firewalld' \
        'flatpak' \
        'git' \
        'gnome-shell-extension-dash-to-dock' \
        'google-chrome-stable' \
        'google-noto-sans-fonts' \
        'google-noto-sans-mono-fonts' \
        'kubectl' \
        'libvirt' \
        'plymouth' \
        'plymouth-scripts' \
        'plymouth-system-theme' \
        'plymouth-theme-spinner' \
        'podman' \
        'qemu-kvm' \
        'skopeo' \
        'terraform' \
        'toolbox' \
        'vim-enhanced' \
        'virt-install' \
        'virt-viewer' \
        'xdg-utils' \
    && dnf clean all \
    && rm -f /etc/yum.repos.d/redhat.repo

# Binary artifact openshift-client 4.22.14 (sha256-verified)
RUN set -eu; \
    tmp="$(mktemp -d)"; \
    curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
        -o "$tmp/download" 'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.22.14/openshift-client-linux-amd64-rhel9-4.22.14.tar.gz'; \
    echo '73d4204fe2d028a5fb3b05f71da174915442c445d3b417321c635bf17d099f6b  '"$tmp/download" | sha256sum --check --strict --quiet -; \
    tar -xzf "$tmp/download" -C "$tmp" --no-same-owner -- 'oc'; \
    install -D -m 0755 "$tmp"/'oc' '/usr/local/bin/oc'; \
    rm -rf "$tmp"

# Image files
COPY rootfs/ /

# System configuration
RUN tmp="$(mktemp -d)" \
    && cp /usr/share/glib-2.0/schemas/*.xml /usr/share/glib-2.0/schemas/50_deskos.gschema.override "$tmp"/ \
    && glib-compile-schemas --strict --dry-run "$tmp" \
    && rm -rf "$tmp" \
    && glib-compile-schemas /usr/share/glib-2.0/schemas \
    && dconf update \
    && systemctl enable 'cockpit.socket' 'firewalld.service' 'gdm.service' \
    && systemctl set-default 'graphical.target'

# Boot splash theme deskos: package-owned frames from /usr/share/plymouth/themes/spinner, then made the default
RUN set -eu; \
    for f in '/usr/share/plymouth/themes/spinner'/*.png; do \
        [ -f "$f" ] || continue; \
        name="$(basename "$f")"; \
        [ "$name" != 'watermark.png' ] || continue; \
        [ ! -e '/usr/share/plymouth/themes/deskos'/"$name" ] || { echo "$name already exists in /usr/share/plymouth/themes/deskos" >&2; exit 1; }; \
        install -m 0644 "$f" '/usr/share/plymouth/themes/deskos'/"$name"; \
    done; \
    [ -e '/usr/share/plymouth/themes/deskos'/throbber-0001.png ] || { echo 'no two-step throbber frames in /usr/share/plymouth/themes/spinner' >&2; exit 1; }; \
    plymouth-set-default-theme 'deskos'; \
    [ "$(plymouth-set-default-theme)" = 'deskos' ] || { echo 'Plymouth default theme is not deskos' >&2; exit 1; }

# Initramfs: rebuilt for every kernel in the image, with plymouth
RUN set -eu; found=0; \
    for kdir in /usr/lib/modules/*/; do \
        [ -e "${kdir}vmlinuz" ] || continue; \
        kver="$(basename "$kdir")"; \
        env DRACUT_NO_XATTR=1 dracut --force "${kdir}initramfs.img" "$kver"; \
        lsinitrd "${kdir}initramfs.img" | grep -q 'plymouthd' || { echo "plymouth missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd "${kdir}initramfs.img" | grep -qF 'usr/share/plymouth/themes/deskos/deskos.plymouth' || { echo "/usr/share/plymouth/themes/deskos/deskos.plymouth missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd "${kdir}initramfs.img" | grep -qF 'usr/share/plymouth/themes/deskos/watermark.png' || { echo "/usr/share/plymouth/themes/deskos/watermark.png missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd "${kdir}initramfs.img" | grep -qF 'usr/share/plymouth/themes/deskos/throbber-0001.png' || { echo "/usr/share/plymouth/themes/deskos/throbber-0001.png missing from initramfs of $kver" >&2; exit 1; }; \
        lsinitrd -f etc/plymouth/plymouthd.conf "${kdir}initramfs.img" | grep -qx 'Theme=deskos' || { echo "initramfs of $kver does not select Plymouth theme deskos" >&2; exit 1; }; \
        found=$((found + 1)); \
    done; \
    [ "$found" -gt 0 ] || { echo 'no kernel found under /usr/lib/modules' >&2; exit 1; }

# Cleanup and bootc validation
RUN rm -rf /var/cache/dnf /var/cache/libdnf5 /var/lib/dnf/repos /var/log/dnf* /var/log/hawkey.log /tmp/* /var/tmp/* \
    && bootc container lint

LABEL org.deskos.platform="rhel-10" \
      org.deskos.workstation="example-devops-rhel10" \
      org.opencontainers.image.title="Example Org DevOps Workstation"
