package theme

import "strings"

// GNOME Shell compiles its theme from SASS to literal hex colors (no CSS
// variables), so a palette is applied by replacing the Adwaita base colors in
// the compiled stylesheet. It is approximate: derived colors (shadows, borders,
// mixes) stay as compiled. shellHexes are the base colors from gnome-shell's
// _default-colors.scss and _palette.scss.
var shellBackgroundHexes = []string{
	"#222226", // $_base_color_dark
	"#36363a", // $bg_color, dark
	"#000000", // $dark_5, the dark panel
	"#241f31", // $dark_4
	"#3d3846", // $dark_3
	"#2e3436", // GTK's classic dark base
	"#fafafb", // $_base_color_light
}

var shellForegroundHexes = []string{
	"#ffffff", // $light_1
	"#f6f5f4", // $light_2
	"#deddda", // $light_3
	"#c0bfbc", // $light_4
	"#9a9996", // $light_5
	"#77767b", // $dark_1
	"#5e5c64", // $dark_2
}

// PatchShellCSS replaces gnome-shell's base colors with the palette.
func PatchShellCSS(css string, p Palette) string {
	pairs := make([]string, 0, 2*len(shellBackgroundHexes)+2*len(shellForegroundHexes))
	add := func(from, to string) {
		if to == "" {
			return
		}
		pairs = append(pairs, from, to, strings.ToUpper(from), to)
	}
	for _, h := range shellBackgroundHexes {
		add(h, p.Background)
	}
	for _, h := range shellForegroundHexes {
		add(h, p.Foreground)
	}
	return strings.NewReplacer(pairs...).Replace(css)
}

// ShellDconf renders the dconf fragment that enables the User Themes
// extension and selects a shell theme pack. extensions is the full
// enabled-extensions list the platform already writes (the fragment must
// repeat it, since dconf does not merge arrays).
func ShellDconf(extensions []string, theme string) string {
	seen := false
	list := make([]string, 0, len(extensions)+1)
	for _, e := range extensions {
		if e == UserThemeExtension {
			seen = true
		}
		list = append(list, gvString(e))
	}
	if !seen {
		list = append(list, gvString(UserThemeExtension))
	}
	return "# Generated by deskos. Do not edit.\n" +
		"[org/gnome/shell]\n" +
		"enabled-extensions=[" + strings.Join(list, ", ") + "]\n\n" +
		"[org/gnome/shell/extensions/user-theme]\n" +
		"name=" + gvString(theme) + "\n"
}

// UserThemeExtension enables a custom GNOME Shell stylesheet.
const UserThemeExtension = "user-theme@gnome-shell-extensions.gcampax.github.com"

// ShellTheme is a shell theme pack name (a directory under
// /usr/share/themes). Two packs exist so the running Shell can be told to
// reload by switching between them.
func ShellTheme(pack string) string { return "deskos-" + pack }
