// Package theme holds the palette-to-artifact generators shared by the
// DeskOS compiler (which bakes them into an image) and the deskos-theme
// command (which applies them to a session). A palette becomes the GTK4
// (libadwaita), GTK3 and terminal overrides a desktop reads.
package theme

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// Palette is the free color set of a theme, palette's shape. The accent is
// not here: it is a GNOME setting (see AccentHex) so the generated CSS and
// the dconf default cannot diverge.
type Palette struct {
	Name       string `json:"name"`
	Background string `json:"background,omitempty"`
	Foreground string `json:"foreground,omitempty"`
	Black      string `json:"black,omitempty"`
	Red        string `json:"red,omitempty"`
	Green      string `json:"green,omitempty"`
	Yellow     string `json:"yellow,omitempty"`
	Blue       string `json:"blue,omitempty"`
	Magenta    string `json:"magenta,omitempty"`
	Cyan       string `json:"cyan,omitempty"`
	White      string `json:"white,omitempty"`
}

// HexColor matches a #RRGGBB color.
var HexColor = regexp.MustCompile(`^#[0-9A-Fa-f]{6}$`)

// accents are libadwaita's nine accent colors (AdwAccentColor), the values
// org.gnome.desktop.interface accent-color accepts, with the hex each maps to.
var accents = []struct {
	name    string
	hex     string
	r, g, b int
}{
	{"blue", "#3584e4", 0x35, 0x84, 0xe4},
	{"teal", "#2190a4", 0x21, 0x90, 0xa4},
	{"green", "#3a944a", 0x3a, 0x94, 0x4a},
	{"yellow", "#c88800", 0xc8, 0x88, 0x00},
	{"orange", "#ed5b00", 0xed, 0x5b, 0x00},
	{"red", "#e62d42", 0xe6, 0x2d, 0x42},
	{"pink", "#d56199", 0xd5, 0x61, 0x99},
	{"purple", "#9141ac", 0x91, 0x41, 0xac},
	{"slate", "#6f8396", 0x6f, 0x83, 0x96},
}

// AccentHex returns the hex of a GNOME accent name.
func AccentHex(name string) (string, bool) {
	for _, a := range accents {
		if a.name == name {
			return a.hex, true
		}
	}
	return "", false
}

// NearestAccent maps a #RRGGBB color to the closest of GNOME's nine accents
// by hue, with a slate fallback for near-achromatic colors.
func NearestAccent(color string) (string, bool) {
	if !HexColor.MatchString(color) {
		return "", false
	}
	hue, sat := rgbToHSL(hexRGB(color))
	if sat < 0.15 {
		return "slate", true
	}
	best, bestDist := "slate", 360.0
	for _, a := range accents {
		ah, _ := rgbToHSL(a.r, a.g, a.b)
		dist := hueDistance(hue, ah)
		if dist < bestDist {
			bestDist, best = dist, a.name
		}
	}
	return best, true
}

// TerminalReady reports whether the palette carries what a terminal palette
// requires: a background, a foreground and the six normal ANSI colors.
func (p Palette) TerminalReady() bool {
	for _, c := range []string{p.Background, p.Foreground, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan} {
		if c == "" {
			return false
		}
	}
	return true
}

// GTK4CSS renders the libadwaita named-color overrides (1.4+). It is
// deliberately conservative: only the window and view surfaces, so libadwaita
// keeps its own hierarchy, contrast and states. The accent is not overridden:
// the Shell and apps follow the native GNOME accent, and a pinned CSS override
// would not follow a user changing it.
func (p Palette) GTK4CSS() string {
	var b strings.Builder
	b.WriteString("/* Generated by deskos. Do not edit. */\n:root {\n")
	write := func(name, value string) {
		if value != "" {
			fmt.Fprintf(&b, "  --%s: %s;\n", name, value)
		}
	}
	write("window-bg-color", p.Background)
	write("window-fg-color", p.Foreground)
	write("view-bg-color", p.Background)
	write("view-fg-color", p.Foreground)
	// libadwaita does not derive the sidebar from the window color, so a theme
	// that sets the window leaves a neutral seam next to it. Step the sidebar
	// toward the foreground (lighter on a dark theme, darker on a light one),
	// which keeps it in the palette's hue.
	if p.Background != "" && p.Foreground != "" {
		write("sidebar-bg-color", mix(p.Background, p.Foreground, 0.08))
		write("sidebar-fg-color", p.Foreground)
	}
	b.WriteString("}\n")
	return b.String()
}

// mix returns a sRGB mix of a and b by weight (0..1) toward b. An invalid
// color is returned unchanged.
func mix(a, b string, weight float64) string {
	if !HexColor.MatchString(a) || !HexColor.MatchString(b) {
		return a
	}
	ar, ag, ab := hexRGB(a)
	br, bg, bb := hexRGB(b)
	return fmt.Sprintf("#%02x%02x%02x",
		int(float64(ar)+weight*float64(br-ar)),
		int(float64(ag)+weight*float64(bg-ag)),
		int(float64(ab)+weight*float64(bb-ab)))
}

// GTK3CSS renders the GTK3 named-color override. It only takes effect when
// the active GTK3 theme (adw-gtk3) consults these names; see the docs.
func (p Palette) GTK3CSS(accent string) string {
	var b strings.Builder
	b.WriteString("/* Generated by deskos. Do not edit. */\n")
	define := func(name, value string) {
		if value != "" {
			fmt.Fprintf(&b, "@define-color %s %s;\n", name, value)
		}
	}
	if hex, ok := AccentHex(accent); ok {
		fg := ContrastForeground(hex)
		for _, n := range []string{"accent_color", "accent_bg_color", "theme_selected_bg_color"} {
			define(n, hex)
		}
		for _, n := range []string{"accent_fg_color", "theme_selected_fg_color"} {
			define(n, fg)
		}
	}
	for _, n := range []string{"theme_bg_color", "theme_base_color", "window_bg_color", "view_bg_color", "headerbar_bg_color", "card_bg_color"} {
		define(n, p.Background)
	}
	for _, n := range []string{"theme_fg_color", "theme_text_color", "window_fg_color", "view_fg_color", "headerbar_fg_color", "card_fg_color"} {
		define(n, p.Foreground)
	}
	return b.String()
}

// PtyxisPalette renders a Ptyxis terminal palette (single scheme). The bright
// half reuses the normal colors; black and white default to background and
// foreground.
func (p Palette) PtyxisPalette() string {
	black, white := p.Black, p.White
	if black == "" {
		black = p.Background
	}
	if white == "" {
		white = p.Foreground
	}
	var b strings.Builder
	fmt.Fprintf(&b, "[Palette]\nName=%s\nPrimary=true\nForeground=%s\nBackground=%s\n", p.Name, p.Foreground, p.Background)
	normal := []string{black, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan, white}
	for i := 0; i < 16; i++ {
		fmt.Fprintf(&b, "Color%d=%s\n", i, normal[i%8])
	}
	return b.String()
}

// PtyxisProfile renders a dconf fragment that points Ptyxis' default profile
// at the palette. The profile keys sit under a relocatable schema, whose
// keyfile group is the bare path (dconf builds /…/<uuid>/palette from it);
// dconf update compiles it from distro.d.
func (p Palette) PtyxisProfile(uuid string) string {
	return fmt.Sprintf("# Generated by deskos. Do not edit.\n"+
		"[org/gnome/Ptyxis]\n"+
		"default-profile-uuid=%s\n"+
		"profile-uuids=[%s]\n\n"+
		"[org/gnome/Ptyxis/Profiles/%s]\n"+
		"palette=%s\n",
		gvString(uuid), gvString(uuid), uuid, gvString(p.Name))
}

// GhosttyConfig renders a Ghostty terminal theme from the palette.
func (p Palette) GhosttyConfig() string {
	black, white := p.Black, p.White
	if black == "" {
		black = p.Background
	}
	if white == "" {
		white = p.Foreground
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by deskos. Do not edit.\nbackground = %s\nforeground = %s\n", p.Background, p.Foreground)
	palette := []string{black, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan, white,
		black, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan, white}
	for i, c := range palette {
		fmt.Fprintf(&b, "palette = %d=%s\n", i, c)
	}
	return b.String()
}

// ContrastForeground picks readable text for a background color.
func ContrastForeground(color string) string {
	r, g, b := hexRGB(color)
	luma := 0.2126*float64(r) + 0.7152*float64(g) + 0.0722*float64(b)
	if luma > 150 {
		return "rgb(0 0 0 / 80%)"
	}
	return "#ffffff"
}

func hexRGB(color string) (int, int, int) {
	r, _ := strconv.ParseUint(color[1:3], 16, 8)
	g, _ := strconv.ParseUint(color[3:5], 16, 8)
	b, _ := strconv.ParseUint(color[5:7], 16, 8)
	return int(r), int(g), int(b)
}

// rgbToHSL returns the HSL hue (degrees) and saturation, used for accent and
// variant math.
func rgbToHSL(r, g, b int) (hue, sat float64) {
	h, s, _ := rgbToHSLFull(r, g, b)
	return h, s
}

func rgbToHSLFull(r, g, b int) (hue, sat, light float64) {
	rf, gf, bf := float64(r)/255, float64(g)/255, float64(b)/255
	max := max3(rf, gf, bf)
	min := min3(rf, gf, bf)
	d := max - min
	light = (max + min) / 2
	if d == 0 {
		return 0, 0, light
	}
	if light > 0.5 {
		sat = d / (2 - max - min)
	} else {
		sat = d / (max + min)
	}
	switch max {
	case rf:
		hue = 60 * mod((gf-bf)/d, 6)
	case gf:
		hue = 60 * ((bf-rf)/d + 2)
	default:
		hue = 60 * ((rf-gf)/d + 4)
	}
	if hue < 0 {
		hue += 360
	}
	return hue, sat, light
}

func hueDistance(a, b float64) float64 {
	d := mod(a-b, 360)
	if d > 180 {
		d = 360 - d
	}
	return d
}

func max3(a, b, c float64) float64 {
	if a >= b && a >= c {
		return a
	}
	if b >= c {
		return b
	}
	return c
}

func min3(a, b, c float64) float64 {
	if a <= b && a <= c {
		return a
	}
	if b <= c {
		return b
	}
	return c
}

// mod is math.Mod without importing math for one call site.
func mod(a, b float64) float64 {
	m := a - b*float64(int(a/b))
	if m < 0 {
		m += b
	}
	return m
}

// gvString renders a GVariant text-format string.
func gvString(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}
