// Package theme holds the palette-to-artifact generators shared by the
// DeskOS compiler (which bakes them into an image) and the deskos-theme
// command (which applies them to a session). A palette becomes the GTK4
// (libadwaita), GTK3 and terminal overrides a desktop reads.
package theme

import (
	"fmt"
	"math"
	"regexp"
	"strconv"
	"strings"
)

// Palette is the free color set of a theme, palette's shape.
type Palette struct {
	Name       string `json:"name"`
	Accent     string `json:"accent,omitempty"`
	Background string `json:"background,omitempty"`
	Foreground string `json:"foreground,omitempty"`
	Black      string `json:"black,omitempty"`
	Red        string `json:"red,omitempty"`
	Green      string `json:"green,omitempty"`
	Yellow     string `json:"yellow,omitempty"`
	Blue       string `json:"blue,omitempty"`
	Magenta    string `json:"magenta,omitempty"`
	Cyan       string `json:"cyan,omitempty"`
	White      string `json:"white,omitempty"`
}

// HexColor matches a #RRGGBB color.
var HexColor = regexp.MustCompile(`^#[0-9A-Fa-f]{6}$`)

// accentPalette is libadwaita's nine accent colors (AdwAccentColor), the
// values org.gnome.desktop.interface accent-color accepts.
var accentPalette = []struct {
	name    string
	r, g, b int
}{
	{"blue", 0x35, 0x84, 0xe4},
	{"teal", 0x21, 0x90, 0xa4},
	{"green", 0x3a, 0x94, 0x4a},
	{"yellow", 0xc8, 0x88, 0x00},
	{"orange", 0xed, 0x5b, 0x00},
	{"red", 0xe6, 0x2d, 0x42},
	{"pink", 0xd5, 0x61, 0x99},
	{"purple", 0x91, 0x41, 0xac},
	{"slate", 0x6f, 0x83, 0x96},
}

// NearestAccent maps a #RRGGBB color to the closest of GNOME's nine accents
// by hue, with a slate fallback for near-achromatic colors.
func NearestAccent(color string) (string, bool) {
	if len(color) != 7 || color[0] != '#' {
		return "", false
	}
	r, err1 := strconv.ParseUint(color[1:3], 16, 8)
	g, err2 := strconv.ParseUint(color[3:5], 16, 8)
	b, err3 := strconv.ParseUint(color[5:7], 16, 8)
	if err1 != nil || err2 != nil || err3 != nil {
		return "", false
	}
	hue, sat := hueSaturation(int(r), int(g), int(b))
	if sat < 0.15 {
		return "slate", true
	}
	best, bestDist := "slate", 360.0
	for _, c := range accentPalette {
		ch, _ := hueSaturation(c.r, c.g, c.b)
		dist := math.Abs(hue - ch)
		if dist > 180 {
			dist = 360 - dist
		}
		if dist < bestDist {
			bestDist, best = dist, c.name
		}
	}
	return best, true
}

// hueSaturation returns the HSL hue in degrees and saturation in [0,1].
func hueSaturation(r, g, b int) (hue, sat float64) {
	rf, gf, bf := float64(r)/255, float64(g)/255, float64(b)/255
	max := math.Max(rf, math.Max(gf, bf))
	min := math.Min(rf, math.Min(gf, bf))
	d := max - min
	if d == 0 {
		return 0, 0
	}
	if l := (max + min) / 2; l > 0.5 {
		sat = d / (2 - max - min)
	} else {
		sat = d / (max + min)
	}
	switch max {
	case rf:
		hue = 60 * math.Mod((gf-bf)/d, 6)
	case gf:
		hue = 60 * ((bf-rf)/d + 2)
	default:
		hue = 60 * ((rf-gf)/d + 4)
	}
	if hue < 0 {
		hue += 360
	}
	return hue, sat
}

// TerminalReady reports whether the palette carries what a terminal palette
// requires: a background, a foreground and the six normal ANSI colors.
func (p Palette) TerminalReady() bool {
	for _, c := range []string{p.Background, p.Foreground, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan} {
		if c == "" {
			return false
		}
	}
	return true
}

// GTK4CSS renders the libadwaita named-color overrides (1.4+) at the GTK4
// user stylesheet. Empty colors leave the Adwaita default.
func (p Palette) GTK4CSS() string {
	var b strings.Builder
	b.WriteString("/* Generated by deskos. Do not edit. */\n:root {\n")
	write := func(name, value string) {
		if value != "" {
			fmt.Fprintf(&b, "  --%s: %s;\n", name, value)
		}
	}
	if p.Accent != "" {
		write("accent-bg-color", p.Accent)
		write("accent-color", p.Accent)
		write("accent-fg-color", ContrastForeground(p.Accent))
	}
	for _, surface := range []string{"window", "view", "headerbar", "card", "sidebar", "popover"} {
		write(surface+"-bg-color", p.Background)
		write(surface+"-fg-color", p.Foreground)
	}
	b.WriteString("}\n")
	return b.String()
}

// GTK3CSS renders the GTK3 named-color override. It only takes effect when
// the active GTK3 theme (adw-gtk3) consults these names.
func (p Palette) GTK3CSS() string {
	var b strings.Builder
	b.WriteString("/* Generated by deskos. Do not edit. */\n")
	define := func(name, value string) {
		if value != "" {
			fmt.Fprintf(&b, "@define-color %s %s;\n", name, value)
		}
	}
	if p.Accent != "" {
		fg := ContrastForeground(p.Accent)
		for _, n := range []string{"accent_color", "accent_bg_color", "theme_selected_bg_color"} {
			define(n, p.Accent)
		}
		for _, n := range []string{"accent_fg_color", "theme_selected_fg_color"} {
			define(n, fg)
		}
	}
	for _, n := range []string{"theme_bg_color", "theme_base_color", "window_bg_color", "view_bg_color", "headerbar_bg_color", "card_bg_color"} {
		define(n, p.Background)
	}
	for _, n := range []string{"theme_fg_color", "theme_text_color", "window_fg_color", "view_fg_color", "headerbar_fg_color", "card_fg_color"} {
		define(n, p.Foreground)
	}
	return b.String()
}

// PtyxisPalette renders a Ptyxis terminal palette (single scheme). The bright
// half reuses the normal colors; black and white default to background and
// foreground.
func (p Palette) PtyxisPalette() string {
	black, white := p.Black, p.White
	if black == "" {
		black = p.Background
	}
	if white == "" {
		white = p.Foreground
	}
	var b strings.Builder
	fmt.Fprintf(&b, "[Palette]\nName=%s\nPrimary=true\nForeground=%s\nBackground=%s\n", p.Name, p.Foreground, p.Background)
	normal := []string{black, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan, white}
	for i := 0; i < 16; i++ {
		fmt.Fprintf(&b, "Color%d=%s\n", i, normal[i%8])
	}
	return b.String()
}

// PtyxisProfile renders a dconf fragment that points Ptyxis' default profile
// at the palette. The profile keys sit under a relocatable schema, whose
// keyfile group is the bare path (dconf builds /…/<uuid>/palette from it);
// dconf update compiles it from distro.d.
func (p Palette) PtyxisProfile(uuid string) string {
	return fmt.Sprintf("# Generated by deskos. Do not edit.\n"+
		"[org/gnome/Ptyxis]\n"+
		"default-profile-uuid=%s\n"+
		"profile-uuids=[%s]\n\n"+
		"[org/gnome/Ptyxis/Profiles/%s]\n"+
		"palette=%s\n",
		gvString(uuid), gvString(uuid), uuid, gvString(p.Name))
}

// GhosttyConfig renders a Ghostty terminal theme from the palette.
func (p Palette) GhosttyConfig() string {
	black, white := p.Black, p.White
	if black == "" {
		black = p.Background
	}
	if white == "" {
		white = p.Foreground
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by deskos. Do not edit.\nbackground = %s\nforeground = %s\n", p.Background, p.Foreground)
	palette := []string{black, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan, white,
		black, p.Red, p.Green, p.Yellow, p.Blue, p.Magenta, p.Cyan, white}
	for i, c := range palette {
		fmt.Fprintf(&b, "palette = %d=%s\n", i, c)
	}
	return b.String()
}

// ContrastForeground picks readable text for a background color.
func ContrastForeground(color string) string {
	r, _ := strconv.ParseUint(color[1:3], 16, 8)
	g, _ := strconv.ParseUint(color[3:5], 16, 8)
	b, _ := strconv.ParseUint(color[5:7], 16, 8)
	luma := 0.2126*float64(r) + 0.7152*float64(g) + 0.0722*float64(b)
	if luma > 150 {
		return "rgb(0 0 0 / 80%)"
	}
	return "#ffffff"
}

// gvString renders a GVariant text-format string.
func gvString(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}
