apiVersion: core.deskos.org/v1alpha1
kind: Workstation
metadata:
  name: deskos-core-centos10
spec:
  displayName: DeskOS Core (CentOS Stream 10)
  platformRef: centos-stream-10
  profiles:
    - deskos-core
    - deskos-reference-apps
