apiVersion: core.deskos.org/v1alpha1
kind: Workstation
metadata:
  name: example-core-almalinux-10
spec:
  displayName: DeskOS Core (AlmaLinux 10)
  platformRef: almalinux-10
  profiles:
    - deskos-core
