#!/usr/bin/env python3
"""Verify the vulnerability exceptions against a fresh Grype report.

The gate opens only for vulnerabilities recorded, owned and dated in
``tests/supply-chain/exceptions.json``. This script makes that record
enforceable, between the raw report and the gate:

* the review date must not have passed;
* the scanned base image must be the one the record was reviewed against;
* every Critical match of an excepted vulnerability must be an exact
  approved combination of package, type, version and location (a new
  binary, a new version or a moved base layer fails the check);
* a Critical that no exception covers is reported too, so the record is the
  single list of what this image accepts;
* a match with no component identification fails the check.

It also emits the Grype gate configuration implied by the record
(``--emit-gate``), so the gate can never drift from what was reviewed.

Exit 0 when the record holds, 1 otherwise, 2 on usage.

Usage:
  check_exceptions.py --cves cves.json --exceptions exceptions.json [--plan plan.json]
  check_exceptions.py --exceptions exceptions.json --emit-gate gate.grype.yaml
"""
from __future__ import annotations

import argparse
import datetime
import json
import sys

CRITICAL = "Critical"


def load_json(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def combos(record):
    """Return the approved {id: {(package, type, version, path)}} set."""
    approved = {}
    for exc in record["exceptions"]:
        entries = set()
        for m in exc["matches"]:
            entries.add((m["package"], m["type"], m["version"], m.get("path", "")))
        approved[exc["id"]] = entries
    return approved


def match_combos(match):
    """Return the (package, type, version, path) combos of one Grype match."""
    artifact = match.get("artifact") or {}
    name = artifact.get("name")
    kind = artifact.get("type")
    version = artifact.get("version")
    if not name or not kind or not version:
        return None
    locations = artifact.get("locations") or [{}]
    return {(name, kind, version, loc.get("path", "")) for loc in locations}


def check(record, cves, plan=None, today=None):
    """Return the list of problems; empty means the record holds."""
    problems = []

    review = datetime.date.fromisoformat(record["review"])
    if (today or datetime.date.today()) > review:
        problems.append(
            f"exception review expired on {record['review']}: re-review tests/supply-chain/exceptions.json"
        )

    if plan is not None:
        base = (plan.get("artifact") or {}).get("baseImage") or {}
        if base.get("digest") != record["base"]["digest"]:
            problems.append(
                "base image changed: scanned "
                f"{base.get('digest')} but the record was reviewed against "
                f"{record['base']['digest']}; re-review the layer paths"
            )

    approved = combos(record)
    for match in cves.get("matches") or []:
        if match["vulnerability"].get("severity") != CRITICAL:
            continue
        vid = match["vulnerability"]["id"]
        found = match_combos(match)
        if found is None:
            problems.append(f"{vid}: match without component identification: {match.get('artifact')}")
            continue
        for combo in sorted(found):
            pkg, kind, version, path = combo
            if vid not in approved:
                problems.append(f"{vid}: Critical not covered by an exception: {pkg} {kind} {version} {path}")
            elif combo not in approved[vid]:
                problems.append(f"{vid}: unapproved match: {pkg} {kind} {version} {path}")
    return problems


def effective_record(record, cves):
    """Return what this scan actually accepted: the observed match combos.

    The reviewed record is a standing approval; a single image may use only
    part of it. This is what the publish attests, so the signed decision
    names the exact matches accepted, not the whole approval.
    """
    approved = combos(record)
    accepted = []
    seen = set()
    for match in cves.get("matches") or []:
        vid = match["vulnerability"]["id"]
        if vid not in approved:
            continue
        found = match_combos(match)
        if found is None:
            continue
        for combo in sorted(found):
            if combo in approved[vid] and (vid,) + combo not in seen:
                seen.add((vid,) + combo)
                pkg, kind, version, path = combo
                accepted.append(
                    {"id": vid, "package": pkg, "type": kind, "version": version, "path": path}
                )
    return {
        "owner": record["owner"],
        "review": record["review"],
        "base": record["base"],
        "accepted": accepted,
    }


def emit_gate(record):
    """Return the Grype configuration that applies the record's exceptions."""
    lines = [
        "# GENERATED by tests/supply-chain/check_exceptions.py --emit-gate.",
        f"# Source of truth: tests/supply-chain/exceptions.json"
        f" (owner: {record['owner']}, review: {record['review']}).",
        "# Do not edit: edit the record and regenerate.",
        "check-for-app-update: false",
        "ignore:",
    ]
    for exc in record["exceptions"]:
        seen = set()
        for m in exc["matches"]:
            key = (m["package"], m["type"], m["version"])
            if key in seen:
                continue
            seen.add(key)
            lines += [
                f"  - vulnerability: {exc['id']}",
                f"    reason: {json.dumps(exc['reason'])}",
                "    package:",
                f"      name: {m['package']}",
                f"      type: {m['type']}",
                f"      version: {m['version']}",
            ]
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cves", help="raw Grype report (JSON)")
    parser.add_argument("--exceptions", required=True, help="the reviewed record")
    parser.add_argument("--plan", help="deskosctl plan.json, to check the base digest")
    parser.add_argument("--emit-gate", metavar="FILE", help="write the Grype gate configuration")
    parser.add_argument("--effective", metavar="FILE", help="write what this scan actually accepted")
    args = parser.parse_args(argv)

    record = load_json(args.exceptions)

    if args.emit_gate:
        with open(args.emit_gate, "w", encoding="utf-8") as fh:
            fh.write(emit_gate(record))
        return 0

    if not args.cves:
        parser.error("--cves is required unless --emit-gate is given")

    cves = load_json(args.cves)
    problems = check(record, cves, load_json(args.plan) if args.plan else None)
    if problems:
        for p in problems:
            print(f"error: {p}", file=sys.stderr)
        return 1
    if args.effective:
        with open(args.effective, "w", encoding="utf-8") as fh:
            json.dump(effective_record(record, cves), fh, indent=2)
            fh.write("\n")
    total = sum(len(e["matches"]) for e in record["exceptions"])
    print(f"ok: {len(record['exceptions'])} exception(s), {total} approved match(es), review {record['review']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
