// Command deskos-theme applies a theme's palette to the GNOME surfaces
// DeskOS supports. It is the runtime counterpart of the compiler's Theme
// kind: the compiler bakes the palette into an image (system mode), and this
// command applies it to a session (user mode), reading an palette theme
// directory.
//
// What it applies is deliberately bounded and documented: the GTK4/GTK3
// files, the terminal palettes and, in user mode, the GNOME settings
// colour-scheme, accent, wallpaper and the Ptyxis profile. The GNOME Shell
// stylesheet is an explicit, experimental opt in (--shell-css).
package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/deskosproject/deskos-core/internal/theme"
)

// ptyxisProfileUUID is the fixed UUID of the profile the tool provisions so a
// terminal uses the palette by default.
const ptyxisProfileUUID = "9a1f0f9a-6f2b-4a0e-8e0b-0d9f4a1c2b30"

const usage = "usage: deskos-theme apply --palette <dir> [--user | --root <dir>] [--shell-css <file>]\n" +
	"       deskos-theme reset-gnome-defaults"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(2)
	}
	switch os.Args[1] {
	case "apply":
		apply(os.Args[2:])
	case "reset-gnome-defaults":
		resetGNOMEDefaults()
	default:
		fmt.Fprintln(os.Stderr, usage)
		os.Exit(2)
	}
}

func apply(args []string) {
	fs := flag.NewFlagSet("apply", flag.ExitOnError)
	palette := fs.String("palette", "", "an palette theme directory (colors.toml + backgrounds)")
	user := fs.Bool("user", false, "write to $HOME and apply the GNOME settings of the session")
	root := fs.String("root", "/", "system root to write under")
	shellCSS := fs.String("shell-css", "", "EXPERIMENTAL: the distro's compiled gnome-shell.css to recolor")
	extensions := fs.String("extensions", "background-logo@fedorahosted.org,dash-to-dock@micxgx.gmail.com",
		"the enabled-extensions the image already writes, to repeat in the shell drop in")
	_ = fs.Parse(args)

	if *palette == "" {
		fmt.Fprintln(os.Stderr, "deskos-theme: --palette is required")
		os.Exit(2)
	}
	p, accent, mode, err := paletteFrompalette(*palette)
	if err != nil {
		fmt.Fprintf(os.Stderr, "deskos-theme: %v\n", err)
		os.Exit(1)
	}

	base := *root
	if *user {
		home, err := os.UserHomeDir()
		if err != nil {
			fmt.Fprintf(os.Stderr, "deskos-theme: %v\n", err)
			os.Exit(1)
		}
		base = home
	}
	files := artifacts(base, *user, p, accent)
	if *shellCSS != "" {
		css, err := os.ReadFile(*shellCSS)
		if err != nil {
			fmt.Fprintf(os.Stderr, "deskos-theme: %v\n", err)
			os.Exit(1)
		}
		patched := theme.PatchShellCSS(string(css), p)
		shellDir := filepath.Join(base, "usr/share/themes")
		dconfPath := ""
		if *user {
			shellDir = filepath.Join(base, ".local/share/themes")
		} else {
			dconfPath = filepath.Join(base, "etc/dconf/db/distro.d/61-deskos-shell")
		}
		for _, pack := range []string{"a", "b"} {
			files[filepath.Join(shellDir, theme.ShellTheme(pack), "gnome-shell/gnome-shell.css")] = patched
		}
		if dconfPath != "" {
			files[dconfPath] = theme.ShellDconf(strings.Split(*extensions, ","), theme.ShellTheme("a"))
		}
	}

	names := make([]string, 0, len(files))
	for n := range files {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		if err := writeFile(n, files[n]); err != nil {
			fmt.Fprintf(os.Stderr, "deskos-theme: %v\n", err)
			os.Exit(1)
		}
		fmt.Println(n)
	}

	if *user {
		if failures := applyUser(*palette, p, accent, mode); failures > 0 {
			fmt.Fprintf(os.Stderr, "deskos-theme: files written, but %d GNOME setting(s) were not applied; the session may still show the previous look\n", failures)
			os.Exit(1)
		}
	}
	if !*user && *root == "/" {
		if err := run("dconf", "update"); err != nil {
			fmt.Fprintf(os.Stderr, "deskos-theme: dconf update failed: %v\n", err)
			os.Exit(1)
		}
	}
	if *user {
		fmt.Printf("applied theme %q (%d files and GNOME settings)\n", p.Name, len(files))
	} else if *root == "/" {
		fmt.Printf("applied theme %q (%d files, dconf updated)\n", p.Name, len(files))
	} else {
		fmt.Printf("staged theme %q (%d files under %s; run dconf update inside that root)\n", p.Name, len(files), *root)
	}
	if *shellCSS == "" {
		fmt.Println("note: the GNOME Shell theme is an experimental opt in (--shell-css); the Shell otherwise follows the GNOME accent.")
	}
	fmt.Println("note: gtk-3.0/gtk.css is generated by default and is experimental: it needs the adw-gtk3 theme active and is not verified.")
}

// paletteFrompalette reads an palette theme's colors.toml into a validated
// palette, the GNOME accent name it maps to, and its colour scheme ("" when
// the theme does not say).
func paletteFrompalette(dir string) (theme.Palette, string, string, error) {
	data, err := os.ReadFile(filepath.Join(dir, "colors.toml"))
	if err != nil {
		return theme.Palette{}, "", "", err
	}
	colors := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		colors[strings.TrimSpace(key)] = strings.Trim(strings.TrimSpace(value), `"'`)
	}
	if colors["background"] == "" || colors["foreground"] == "" {
		return theme.Palette{}, "", "", fmt.Errorf("%s does not define background and foreground", dir)
	}
	// Every value that reaches a CSS or a config file is a validated hex.
	for _, key := range []string{"background", "foreground", "red", "green", "yellow", "blue", "magenta", "cyan"} {
		if v := colors[key]; v != "" && !theme.HexColor.MatchString(v) {
			return theme.Palette{}, "", "", fmt.Errorf("%s: %s=%q is not a #RRGGBB color", dir, key, v)
		}
	}
	p := theme.Palette{
		Name:       filepath.Base(filepath.Clean(dir)),
		Background: colors["background"], Foreground: colors["foreground"],
		Red: colors["red"], Green: colors["green"], Yellow: colors["yellow"],
		Blue: colors["blue"], Magenta: colors["magenta"], Cyan: colors["cyan"],
	}
	accent := ""
	if hex := colors["accent"]; hex != "" {
		if !theme.HexColor.MatchString(hex) {
			return theme.Palette{}, "", "", fmt.Errorf("%s: accent=%q is not a #RRGGBB color", dir, hex)
		}
		if name, ok := theme.NearestAccent(hex); ok {
			accent = name
		}
	}
	mode := colors["mode"]
	if mode != "" && mode != "dark" && mode != "light" {
		return theme.Palette{}, "", "", fmt.Errorf("%s: mode=%q is not dark or light", dir, mode)
	}
	return p, accent, mode, nil
}

// artifacts returns the absolute paths and contents to write. System mode
// seeds the user skeleton and the dconf database a build's dconf update
// compiles; user mode writes the same files into a running session.
func artifacts(base string, user bool, p theme.Palette, accent string) map[string]string {
	var skel, dconf string
	if user {
		skel = base
	} else {
		skel = filepath.Join(base, "etc/skel")
		dconf = filepath.Join(base, "etc/dconf/db/distro.d")
	}
	files := map[string]string{
		filepath.Join(skel, ".config/gtk-4.0/gtk.css"): p.GTK4CSS(),
		filepath.Join(skel, ".config/gtk-3.0/gtk.css"): p.GTK3CSS(accent),
	}
	if p.TerminalReady() {
		files[filepath.Join(skel, ".local/share/org.gnome.Ptyxis/palettes", p.Name+".palette")] = p.PtyxisPalette()
		files[filepath.Join(skel, ".config/ghostty/themes", p.Name)] = p.GhosttyConfig()
		if dconf != "" {
			files[filepath.Join(dconf, "60-deskos-ptyxis")] = p.PtyxisProfile(ptyxisProfileUUID)
		}
	}
	return files
}

// applyUser applies what a user session needs beyond the files: the wallpaper
// (copied from the theme), the GNOME settings, and the Ptyxis profile that
// selects the palette. It returns how many settings could not be applied, so
// the command never reports success on a partial failure.
func applyUser(dir string, p theme.Palette, accent string, mode string) int {
	home, err := os.UserHomeDir()
	if err != nil {
		return 1
	}
	failures := 0
	set := func(schema, key, value string) {
		if err := run("gsettings", "set", schema, key, value); err != nil {
			fmt.Printf("deskos-theme: gsettings set %s %s: %v\n", schema, key, err)
			failures++
		}
	}
	if bg := firstBackground(dir); bg != "" {
		dest := filepath.Join(home, ".local/share/deskos/backgrounds", p.Name+filepath.Ext(bg))
		if err := copyFile(bg, dest); err != nil {
			fmt.Printf("deskos-theme: wallpaper %s: %v\n", bg, err)
			failures++
		} else {
			uri := "file://" + dest
			set("org.gnome.desktop.background", "picture-uri", uri)
			set("org.gnome.desktop.background", "picture-uri-dark", uri)
			set("org.gnome.desktop.screensaver", "picture-uri", uri)
		}
	}
	// Only the fields the theme actually carries: an absent mode sets nothing.
	if mode != "" {
		set("org.gnome.desktop.interface", "color-scheme", "prefer-"+mode)
	}
	if accent != "" {
		set("org.gnome.desktop.interface", "accent-color", accent)
	}
	if p.TerminalReady() {
		// Read the user's Ptyxis state first. If either read fails, or the
		// value is not a recognizable list, leave Ptyxis untouched: writing a
		// fresh list would drop the user's profiles.
		uuidsRaw, readU := dconfRead("/org/gnome/Ptyxis/profile-uuids")
		uuids, parseU := gvariantStrings(uuidsRaw)
		defRaw, readD := dconfRead("/org/gnome/Ptyxis/default-profile-uuid")
		defs, parseD := gvariantStrings(defRaw)
		if !readU || !parseU || !readD || !parseD {
			fmt.Println("note: could not read the Ptyxis profile keys; left Ptyxis unchanged")
			failures++
		} else {
			dwrite := func(path, value string) {
				if err := run("dconf", "write", path, value); err != nil {
					fmt.Printf("deskos-theme: dconf write %s: %v\n", path, err)
					failures++
				}
			}
			// Add the DeskOS profile only if it is missing, and keep the
			// user's default profile instead of replacing it.
			if !slices.Contains(uuids, ptyxisProfileUUID) {
				uuids = append(uuids, ptyxisProfileUUID)
			}
			dwrite("/org/gnome/Ptyxis/profile-uuids", gvariantStringList(uuids))
			if len(defs) == 0 {
				dwrite("/org/gnome/Ptyxis/default-profile-uuid", gvariantString(ptyxisProfileUUID))
			} else {
				fmt.Println("note: kept the user's Ptyxis default profile; the DeskOS palette is installed and selectable")
			}
			dwrite("/org/gnome/Ptyxis/Profiles/"+ptyxisProfileUUID+"/palette", gvariantString(p.Name))
		}
	}
	return failures
}

func gvariantString(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}

// dconfRead returns the value at path (GVariant text) and whether the read
// succeeded. An unset key is a successful read of an empty value.
func dconfRead(path string) (string, bool) {
	out, err := exec.Command("dconf", "read", path).Output()
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(out)), true
}

// gvariantStrings parses a GVariant string array like "['a', 'b']". It returns
// ok=false when the value is not a recognizable array, so a malformed read is
// never mistaken for an empty list; an unset key is the empty value and is a
// valid empty list.
func gvariantStrings(v string) (items []string, ok bool) {
	v = strings.TrimSpace(v)
	if v == "" || v == "[]" || v == "@as []" {
		return nil, true
	}
	if !strings.HasPrefix(v, "[") || !strings.HasSuffix(v, "]") {
		return nil, false
	}
	body := strings.TrimSpace(v[1 : len(v)-1])
	for body != "" {
		if body[0] != '\'' {
			return nil, false
		}
		rest := body[1:]
		j := strings.IndexByte(rest, '\'')
		if j < 0 {
			return nil, false
		}
		items = append(items, rest[:j])
		body = strings.TrimSpace(rest[j+1:])
		if body == "" {
			break
		}
		if body[0] != ',' {
			return nil, false
		}
		body = strings.TrimSpace(body[1:])
	}
	return items, true
}

func gvariantStringList(items []string) string {
	parts := make([]string, len(items))
	for i, s := range items {
		parts[i] = gvariantString(s)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// firstBackground returns the theme's first background image, if any.
func firstBackground(dir string) string {
	entries, err := os.ReadDir(filepath.Join(dir, "backgrounds"))
	if err != nil {
		return ""
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		switch strings.ToLower(filepath.Ext(e.Name())) {
		case ".png", ".jpg", ".jpeg", ".svg", ".webp":
			names = append(names, e.Name())
		}
	}
	if len(names) == 0 {
		return ""
	}
	sort.Strings(names)
	return filepath.Join(dir, "backgrounds", names[0])
}

func copyFile(src, dest string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dest, data, 0o644)
}

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
	return cmd.Run()
}

func writeFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// resetGNOMEDefaults returns the GNOME keys DeskOS manages to the image
// default. Its scope is exactly that: it resets those keys whether or not the
// user set them, and it does not remove the files deskos-theme wrote under
// $HOME.
func resetGNOMEDefaults() {
	failures := 0
	for _, k := range [][2]string{
		{"org.gnome.desktop.interface", "color-scheme"},
		{"org.gnome.desktop.interface", "accent-color"},
		{"org.gnome.desktop.background", "picture-uri"},
		{"org.gnome.desktop.background", "picture-uri-dark"},
		{"org.gnome.desktop.screensaver", "picture-uri"},
	} {
		if err := run("gsettings", "reset", k[0], k[1]); err != nil {
			fmt.Printf("deskos-theme: gsettings reset %s %s: %v\n", k[0], k[1], err)
			failures++
		}
	}
	if failures > 0 {
		fmt.Fprintf(os.Stderr, "deskos-theme: %d key(s) could not be reset\n", failures)
		os.Exit(1)
	}
	fmt.Println("reset the GNOME keys DeskOS manages; the files under $HOME are untouched")
}
